### PR TITLE
check tagName existence prior to use, fixes #62

### LINKED ISSUE #62: replaceCustomElements fails with a VirtualText node
`vtree.tagName` is undefined so calling `toUpperCase()` fails with:

> Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

So check for existence prior to use.

introduced in commit: 6c801af9c880be4744c8d48a1a1b5fe80b3df13d

:beers:

### PR DESCRIPTION
**Pull request by dobrite**
Fixes #62 

:beers:

### CODE REVIEW

**Comment by staltz** [comment]
What was your use case? I want to make a test for this as well.

**Comment by dobrite** [comment]
[Modified custom-elements.js example](https://gist.github.com/dobrite/595586fa2c4d795c7111#file-gistfile1-js-L74) :+1:

**Comment by staltz** [comment]
I fixed it in a slightly different way, so I won't merge this, but it's fixed. :+1:
https://github.com/staltz/cycle/commit/273edeac94cf78bde94a9a06028c5e9cd178682c

**Comment by dobrite** [comment]
Awesome, thanks! :grinning:

**Pull request closed without merging**
